### ISSUE TITLE
exporting bitfield state as 32 bits integers

### ISSUE THREAD

**Issue by ad34** [fb55/bitfield#19]
I started using the module and it works fine but I have some issue while trying to use it with another language language (lua)

Programmers of the lua code asked me to export the bitfield (we need 128 values) as 4 integers and I have trouble doing this.

Seems like read from the buffer with readUInt32LE give unexpected results. 

So I started investigating on this and notice there is a that trick :  128 >> (i % 8)

so creating a buffer of 128 bool and sending the index 0 to true give this :

> var f  = new bitfield(128)
> f.set(0)
>f.buffer
<Buffer 80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>

if you only set(1)

<Buffer 40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00>

It makes sense if you read the code but I dont get the point of this trick and it s not easy to understand which bits are set if you looks at the buffer dump

I tried to find a way to export the data is the more easily undestable way but without success

for exemple lua programmers expect the output if I set the first bool to 1 only to be : 

u32exports = [1,0,0,0]

**Comment by feross** [comment]
The whole point of this package is to compactly store bits in a larger buffer. It's expected that when you view the buffer as a bunch of 32 bit ints it will look like nonsense.

I don't know what to tell you.

**Comment by feross** [comment]
If you want to get a friendly array, loop over the BitField using `b.get(i)` to extract the values and put them into an array yourself.

**Comment by ad34** [comment]
got it , but why set set(0) set the  most significant bit ? why not using  (1 << (i % 8)) 

if other has the same kind of issue, to export as 32 bits integers , you can use  swap32() on the buffer

**Comment by feross** [comment]
It sets bits from left to right, because that's the most useful for building up a bitfield when working with low-level wire protocols.
