### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by jimmywarting** [fb55/bitfield#25]
https://github.com/fb55/bitfield/blob/0ba8d2da2bcd268f61ec709b3ed1fa8b384abbb6/index.js#L35-L62

@ line 50 `this.buffer.length < length` should not be necessary since, line 38 already dose this check

I'm curious also when you grow the buffer, why don't you use `set`?
e.g. like so:
```js
BitField.prototype._grow = function (length) {
  if (length <= this.grow) {
    var newBuffer = new Container(length) // eslint-disable-line node/no-deprecated-api
    if (newBuffer.fill) newBuffer.fill(0)
    newBuffer.set(newBuffer)
    this.buffer = newBuffer
  }
}
```

Another thing: is Buffer really necessary? Can we not only use Uint8Array? A Buffer adds other overhead functionality that seems unnecessary. `new Buffer(n)` is also deprecated and i don't think we need `fill(0)` either if we just use Uint8Array...

https://github.com/fb55/bitfield/blob/0ba8d2da2bcd268f61ec709b3ed1fa8b384abbb6/index.js#L1-L3

BitField is shared between frontend or backend so can't we not just stick to using Uint8Array so we can expect the same thing in both environments.
Not having to worry about when buffer constructor is removed completely from Node and replaced with just an object

I also think `_grow` can be factored out of the class to just be a helper function that returns a value or simply be put inlined since it is only used at one place

```js
if (this.buffer.length < j + 1) {
  // before:
  // this._grow(Math.max(j + 1, Math.min(2 * this.buffer.length, this.grow)))
  
  var buffer = new Uint8Array(Math.max(j + 1, Math.min(2 * this.buffer.length, this.grow)))
  buffer.set(this.buffer)
  this.buffer = buffer
}
```

<details>
<summary>es6 version</summary>

```js
function getByteSize (num) {
  let out = num >> 3
  if (num % 8 !== 0) out++
  return out
}

class BitField {
  constructor (data = 0, {grow} = {}) {
    this.grow = (grow && isFinite(grow) && getByteSize(grow)) || 0
    this.buffer = typeof data === 'number' ? new Uint8Array(getByteSize(data)) : data
  }

  get (i) {
    const j = i >> 3
    return (j < this.buffer.length) &&
      !!(this.buffer[j] & (128 >> (i % 8)))
  }

  set (i, b = 1) {
    const j = i >> 3
    if (b) {
      if (this.buffer.length < j + 1) {
        const length = Math.max(j + 1, Math.min(2 * this.buffer.length, this.grow))
        if (length <= this.grow) {
          const newBuffer = new Uint8Array(length)
          newBuffer.set(this.buffer)
          this.buffer = newBuffer
        }
      }
      // Set
      this.buffer[j] |= 128 >> (i % 8)
    } else if (j < this.buffer.length) {
      // Clear
      this.buffer[j] &= ~(128 >> (i % 8))
    }
  }
}

if (typeof module !== 'undefined') module.exports = BitField
```

</details>

**Comment by fb55** [comment]
Hi Jimmy, PRs welcome! Happy to upgrade this library to ES6.

**Comment by feross** [comment]
@jimmywarting Thanks for the awesome PR. Closing this issue now.

**Comment by feross** [comment]
@jimmywarting Can you send a PR with the code you used to benchmark the performance? If you add it in a `perf/` folder, we can add it to `.npmignore` so it doesn't get published to npm.
