### ISSUE TITLE
How to init a Bitfield starting from a binary?

### ISSUE THREAD

**Issue by FezVrasta** [fb55/bitfield#284]
I’d like to use this library to read a Transmission pieces bitfield, they provide a base64 encoded binary (pieces) and its pieces size (pieceSize), how would I go to use this library to read it?

**Comment by FezVrasta** [comment]
Thanks! I'm using this to render a chart similar to the one used by Transmission to show the downloaded pieces and this library really simplified the logic.

If you are interested to see the result, it will be available soon on the Raycast' Transmission extension.

**Comment by fb55** [comment]
Very cool, thanks for sharing :)
