### ISSUE TITLE
Bitfield is not a constructor

### ISSUE THREAD

**Issue by cyrusadkisson** [fb55/bitfield#90]
I'm having issues getting this package to work. I've installed with "node install bitfield" and then created the sample program, directly from the readme:

```
import Bitfield from "bitfield";

const field = new Bitfield(256); // Create a bitfield with 256 bits.

field.set(128); // Set the 128th bit.
field.set(128, true); // Same as above.

field.get(128); // `true`
field.get(200); // `false` (all values are initialised to `false`)
field.get(1e3); // `false` (out-of-bounds is also false)

field.set(128, false); // Set the 128th bit to 0 again.

field.buffer; // The buffer used by the bitfield.
```

I created a package.json with {"type":"module"} in the working directory and executed, but I get this:

```
file:///home/myname/eclipse-workspace/myproject/buildTest.js:3
const field = new Bitfield(256); // Create a bitfield with 256 bits.
              ^

TypeError: Bitfield is not a constructor
    at file:///home/myname/eclipse-workspace/myproject/buildTest.js:3:15
    at ModuleJob.run (internal/modules/esm/module_job.js:152:23)
    at async Loader.import (internal/modules/esm/loader.js:166:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```
I'm no node expert so it's entirely possible (probable?) that I'm doing something very obvious re: environment or what-have-you. Could someone give me an assist?

**Comment by king-11** [comment]
Were you able to resolve this

**Comment by fb55** [comment]
This seems like an issue with using CommonJS packages in an ESM environment. I have added an ESM build in #311, which should fix this.

**Comment by king-11** [comment]
Thanks a lot for quick resolution 🌟🔥
